### PR TITLE
Fix scrolling with the Home key

### LINKED ISSUE #167: Home button
Hello, great thanks for extension, but Home-button doesn't work. Only Ctr+Home(((

### PR DESCRIPTION
**Pull request by russelldavis**
Fixes #167

### CODE REVIEW

**Comment by russelldavis** [comment]
I have some more fixes and improvements at my fork at https://github.com/russelldavis/HN-Hotkeys/

**Comment by galambalazs** [comment]
@russelldavis thank you. Are you using it on your computer? No other compatibility issues on other websites by changing `overflowing` to `root`

**Comment by russelldavis** [comment]
There was one issue with certain rare quirks-mode sites that I fixed by just disabling smooth scrolling on them: https://github.com/russelldavis/smoothscroll/commit/45966c38e029ddb72789941baa9f49d72313add5

There's a handful of other issues I addressed in my fork, but I don't thiiink any of them were related to this.

**Comment by gblazex** [comment]
this has been fixed in the latest release, many thanks Russel for contributing 💓

**Pull request closed without merging**
